### ISSUE TITLE
New decorators

### ISSUE THREAD

**Issue by Garikolc** [onexus/onexus#18]
A new decorator to set a definible color to a column independently of the type.

A new decorator with definible colors for definible string values.

**Comment by jordeu** [comment]
Examples of use:

The CATEGORICAL color decorator:

``` xml
 <decorator>CATEGORICAL(default="[0,0,0]", map="[panel]=[255,0,0]|[research]=[0,255,0]")</decorator>
```

The UNIFORM color decorator

``` xml
<decorator>UNIFORM(color="[0,255,0]")</decorator>
```
