### ISSUE TITLE
Authorize some roles

### ISSUE THREAD

**Issue by Garikolc** [onexus/onexus#38]
Let authorization tag take some role params like 
<authorization>admin,doctor,customer</authorization>

**Comment by jordeu** [comment]
Some examples:

``` xml
 <authorization>
      role1 AND (role2 OR NOT role3)
 </authorization>
```

It's also posible to use ! as NOT and a comma as AND, like this:

``` xml
<authorization>
    role1, !role2
</authorization>
```

is equal to:

``` xml
<authorization>
    role1 AND NOT role2
</authorization>
```
